export const NUM_OF_GUESSES_ALLOWED = 6;
export const GUESS_LENGTH = 5;

export const KEYBOARD_FIRST_ROW_LETTERS = "QWERTYUIOP";
export const KEYBOARD_SECOND_ROW_LETTERS = "ASDFGHJKL";
export const KEYBOARD_THIRD_ROW_LETTERS = "ZXCVBNM";
